networks:
  traefik_net:
    name: "traefik_net"
    driver: bridge

services:
  
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik_net
    environment:
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUME_PATH_TRAEFIK}/traefik.yml:/traefik.yml:ro
      - ${VOLUME_PATH_TRAEFIK}/secrets/dashboard.htpasswd:/run/secrets/dashboard.htpasswd:ro
      - ${VOLUME_PATH_TRAEFIK}/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.usersfile=/run/secrets/dashboard.htpasswd"
    command:
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"

  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - "no-new-privileges:true"
    user: "1000"
    networks:
      - traefik_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${VOLUME_PATH_PORTAINER}:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"